source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(('django.contrib.auth.urls', 'accounts'), namespace='accounts')),
    path('', include('webapp.urls', namespace='webapp'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import UserDetailView, UserUpdateView, AuthorListView, AuthorDetailView, AuthorCreateView, \
    AuthorUpdateView, AuthorDeleteView, BookListView, BookDetailView, BookCreateView, BookUpdateView, \
    BookDeleteView, ReviewUpdateView, ReviewDeleteView, ReviewCreateView
app_name = 'webapp'

urlpatterns = [
    path('user/<int:pk>/', UserDetailView.as_view(), name='user_details'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user_update'),
    path('authors/', AuthorListView.as_view(), name='author_list'),
    path('authors/<int:pk>/', AuthorDetailView.as_view(), name='author_details'),
    path('authors/create/', AuthorCreateView.as_view(), name='author_create'),
    path('authors/<int:pk>/update/', AuthorUpdateView.as_view(), name='author_update'),
    path('authors/<int:pk>/delete/', AuthorDeleteView.as_view(), name='author_delete'),
    path('', BookListView.as_view(), name='book_list'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_details'),
    path('books/create/', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('books/<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
    path('book/<int:pk>/review/create/', ReviewCreateView.as_view(), name='review_create'),
    path('review/<int:pk>/update', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete', ReviewDeleteView.as_view(), name='review_delete'),
]

source/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Author(models.Model):
    name = models.CharField(max_length=300, verbose_name="ФИО")
    birth_date = models.DateField(null=True, blank=True, verbose_name="Дата рождения")
    death_date = models.DateField(null=True, blank=True, verbose_name="Дата смерти")
    bio = models.TextField(max_length=5000, null=True, blank=True, verbose_name="Биография")
    image = models.ImageField(upload_to='author_images', blank=True, null=True, verbose_name="Фото")
    is_deleted = models.BooleanField(default=False)

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def get_absolute_url(self):
        return reverse('webapp:author_details', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class Book(models.Model):
    title = models.CharField(max_length=300, verbose_name="Название книги")
    author = models.ForeignKey(Author, related_name="books", verbose_name="Автор", on_delete=models.CASCADE)
    published_at = models.CharField(max_length=6, verbose_name="Год издания")
    file = models.FileField(upload_to='book_files', blank=True, null=True, verbose_name="Файл")
    image = models.ImageField(upload_to='book_images', blank=True, null=True, verbose_name="Обложка")
    description = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Описание')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('webapp:book_details', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = "Книга"
        verbose_name_plural = "Книги"


class Review(models.Model):
    text = models.TextField(max_length=3000, null=True, blank=True, verbose_name="Отзыв")
    author = models.ForeignKey(User, verbose_name="Автор", on_delete=models.CASCADE)
    book = models.ForeignKey(Book, related_name="reviews", blank=True, verbose_name="Книга", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, verbose_name="Дата-время создания")

    def get_absolute_url(self):
        return reverse('webapp:book_details', kwargs={'pk': self.book.id})

    def __str__(self):
        return f"{self.pk}. {self.text} | {self.author.username}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

source/webapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Author, Book, Review


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AuthorForm(forms.ModelForm):
    def clean(self):
        if not self.cleaned_data['name']:
            raise forms.ValidationError('Поле "ФИО" должно быть заполнено')
        return super().clean()

    class Meta:
        model = Author
        fields = ['name', 'birth_date', 'death_date', 'bio', 'image']


class BookForm(forms.ModelForm):
    def clean(self):
        if not self.cleaned_data['title'] or not self.cleaned_data['author'] or not self.cleaned_data['published_at']:
            raise forms.ValidationError('Поля "название", "автор" и "год издания" должны быть заполнены')
        return super().clean()

    class Meta:
        model = Book
        fields = ['title', 'author', 'published_at', 'file', 'image', 'description']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text']

source/webapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from webapp.forms import UserForm, AuthorForm, BookForm, ReviewForm
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from webapp.models import Author, Book, Review
from django.urls import reverse_lazy


class UserDetailView(DetailView):
    template_name = 'user_details.html'
    model = User


class UserUpdateView(UpdateView, LoginRequiredMixin, PermissionRequiredMixin):
    model = User
    template_name = 'user_update.html'
    form_class = UserForm

    def get_success_url(self):
        return reverse('webapp:user_details', kwargs={'pk': self.object.pk})

    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        if user != self.request.user:
            return HttpResponseRedirect(reverse('webapp:user_details', kwargs={'pk': pk}))
        return super().get(request, pk=pk)

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author


class AuthorDetailView(DetailView):
    template_name = 'author_details.html'
    model = Author

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context['books_by_author'] = self.object.books.all()
        return context


class AuthorListView(ListView):
    template_name = 'author_list.html'
    model = Author
    queryset = Author.objects.filter(is_deleted=False)


class AuthorCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'author_create.html'
    form_class = AuthorForm
    model = Author

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'author_update.html'
    form_class = AuthorForm
    model = Author

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class AuthorDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'author_delete.html'
    model = Author
    success_url = reverse_lazy('webapp:author_list')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookDetailView(DetailView):
    template_name = 'book_details.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context['book_reviews'] = self.object.reviews.all().order_by('-created_at')
        return context


class BookListView(ListView):
    template_name = 'book_list.html'
    model = Book


class BookCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'book_create.html'
    form_class = BookForm
    model = Book

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'book_update.html'
    form_class = BookForm
    model = Book

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class BookDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = 'book_delete.html'
    model = Book
    success_url = reverse_lazy('webapp:book_list')

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_staff


class ReviewListView(ListView):
    template_name = 'review_list.html'
    model = Review


class ReviewDetailView(DetailView):
    template_name = 'review_detail.html'
    model = Review


class ReviewCreateView(CreateView, LoginRequiredMixin, PermissionRequiredMixin):
    template_name = 'partial/review_form.html'
    form_class = ReviewForm
    model = Review

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user.is_authenticated

    def form_valid(self, form):
        book = get_object_or_404(Book, pk=self.kwargs['pk'])
        form.instance.book = book
        form.instance.author = self.request.user
        return super().form_valid(form)


class ReviewUpdateView(UpdateView, LoginRequiredMixin, PermissionRequiredMixin):
    template_name = 'review_update.html'
    form_class = ReviewForm
    model = Review

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author


class ReviewDeleteView(DeleteView, LoginRequiredMixin, PermissionRequiredMixin):
    template_name = 'review_delete.html'
    model = Review
    success_url = reverse_lazy('webapp:book_list')

    def get_permission_required(self):
        return None

    def has_permission(self):
        return self.request.user == self.get_object().author

source/webapp/templates/author_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Новый автор{% endblock %}

{% block content %}
    <h3 class="mt-3">Добавить автора</h3>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:author_create' %}">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>

{% endblock %}

source/webapp/templates/author_delete.html
{% extends 'base.html' %}

{% block title %}Удалить автора{% endblock %}

{% block content %}
    <h3 class="mt-3">Удаление автора</h3>
    <h5 class="mt-3">Вы уверены, что хотите удалить автора "{{ author.name }}"?</h5>
    <form action="{% url 'webapp:author_delete' author.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2 mr-1">Удалить</button>
        <a class="btn btn-primary mt-2" href="{% url 'webapp:author_list' %}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/author_details.html
{% extends 'base.html' %}

{% block title %}Автор{% endblock %}

{% block content %}
    <h1 class="mt-3">{{ author.name }}</h1>
    <p class="text-secondary">{{ author.birth_date }} - {{ author.death_date }}
        {% if user.is_staff %}
            <a class="float-right" href="{% url 'webapp:author_delete' author.pk %}">Удалить</a>
            <a class="float-right mr-1" href="{% url 'webapp:author_update' author.pk %}">Редактировать |</a>
        {% endif %}
    </p>
    {% if author.image %}
        <div class="img-wrapper">
            <img class="w-50" src="{{ author.image.url }}" alt="{{ author.image.name }}">
        </div>
    {% endif %}
    <p class="mt-3">{{ author.bio }}</p>
    <h2>Книги автора</h2>
    {% include 'partial/books.html' with book_list=books_by_author %}
{% endblock %}

source/webapp/templates/author_list.html
{% extends 'base.html' %}

{% block title %}Aвторы{% endblock %}

{% block content %}
    <div class="row">
        {% for author in author_list %}
            <div class="col col-6">
                <div class="card mt-3">
                    <div class="card-header">
                        <h2 class="card-title card-text"><a href="{% url 'webapp:author_details' author.pk %}" class="card-link">{{ author.name }}</a></h2>
                    </div>
                    {% if author.image %}
                        <div class="card-body">
                            <div class="img-wrapper">
                                <img class="card-img w-50" src="{{ author.image.url }}" alt="{{ author.image.name }}">
                            </div>
                        </div>
                    {% endif %}
                    <div class="card-footer">
                        <p class="card-text">{{ author.birth_date }} - {{ author.death_date }}
                            {% if user.is_staff %}
                                <a class="float-right" href="{% url 'webapp:author_delete'  author.pk %}">Удалить</a>
                                <a class="float-right mr-1" href="{% url 'webapp:author_update' author.pk %}">Редактировать |</a>
                            {% endif %}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/author_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменить информацию об авторе{% endblock %}

{% block content %}
    <h3 class="mt-3">Изменить информацию об авторе</h3>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:author_update' object.pk %}">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>
{% endblock %}

source/webapp/templates/book_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Новая книга{% endblock %}

{% block content %}
    <h3 class="mt-3">Добавить книгу</h3>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:book_create' %}">
        {% csrf_token %}
        {{ form|crispy }}
    <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>
{% endblock %}

source/webapp/templates/book_delete.html
{% extends 'base.html' %}

{% block title %}Удалить книгу{% endblock %}

{% block content %}
    <h3 class="mt-3">Удаление книги</h3>
    <h5 class="mt-4">Вы уверены, что хотите удалить книгу "{{   book.title }}"?</h5>
    <form action="{% url 'webapp:book_delete' book.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary mt-2 mr-1">Удалить</button>
        <a class="btn btn-primary mt-2" href="{% url 'webapp:book_list' %}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/book_list.html
{% extends 'base.html' %}

{% block title %}Список книг{% endblock %}

{% block content %}
    <h2 class="mt-3">Список книг</h2>
    {% include 'partial/books.html' %}

{% endblock %}

source/webapp/templates/review_delete.html
{% extends 'base.html' %}

{% block title %}Удалить отзыв{% endblock %}

{% block content %}
    <h3 class="mt-3">Удаление отзыва</h3>
    <h5 class="mt-3">Вы уверены, что хотите удалить отзыв?</h5>
    <form action="{% url 'webapp:review_delete' review.pk %}" method="post">
        {% csrf_token %}
        <button type="submit mt-2" class="btn btn-primary">Удалить</button>
        <a class="btn btn-primary mt-2" href="{% url 'webapp:book_list' %}" role="button">Отмена</a>
    </form>
{% endblock %}

source/webapp/templates/review_detail.html
{% extends 'base.html' %}

{% block title %}Отзыв{% endblock %}

{% block content %}
    <p>{{ review.author }} | {{ review.created_at }}
        {% if user == review.author %}
            <a class="float-right" href="{% url 'webapp:review_update' article.pk %}">Редактировать</a>
            <a class="float-right" href="{% url 'webapp:review_delete' article.pk %}">Удалить</a>
        {% endif %}
    </p>
    <p class="mt-3 pre-spaces">{{ review.text }}</p>
{% endblock %}

source/webapp/templates/review_list.html
{% block content %}
    <h3 class="mt-3 mr-1">Список отзывов</h3>
    {% include 'partial/reviews.html' %}
{% endblock %}

source/webapp/templates/review_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Изменить отзыв{% endblock %}

{% block content %}
    <h3 class="mt-3 mr-2">Изменить отзыв</h3>
    <form method="post" enctype="multipart/form-data" action="{% url 'webapp:review_update' object.pk %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary mr-1">Отправить</button>
    </form>
{% endblock %}

source/webapp/templates/user_details.html
{% extends 'base.html' %}
{% block title %}Страница пользователя{% endblock %}
{% block content %}
    <div>
        <h3 class="card-title mt-3">Страница пользователя</h3>
        <p>Логин: {{ user }}</p>
        <p>Имя: {{ user.first_name }}</p>
        <p>Фамилия: {{ user.last_name }}</p>
        <p>Почта: {{ user.email }}</p>

        {% if user == request.user %}
            <a class="btn btn-primary mt-2" href="{% url 'webapp:user_update' request.user.pk %}" role="button">Редактировать</a>
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/user_update.html
{% extends 'base.html' %}

{% block title %}Изменить пользователя{% endblock %}

{% block content %}
    <h3 class="mt-3">Изменить пользователя</h3>
    <form action="{% url 'webapp:user_update' form.instance.pk %}" method="post" class="form-group" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row mt-3">
            <div class="col">
              <input type="text" class="form-control" placeholder="First name" name="first_name" value="{{ user.first_name }}">
            </div>
            <div class="col">
              <input type="text" class="form-control" placeholder="Last name" name="last_name" value="{{ user.last_name }}">
            </div>
          </div>
          <div class="form-group mt-3">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="email" value={{ user.email }}>
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
{% endblock %}